version: "3.5"
services:
  whisper:
    build:
      context: ./
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  


